"""Modular, behavior-compatible causal label queue implementation."""

from .cli import eligible_indices, main
from .estimators import (
    gsc_output,
    normalized_python_labels,
    python_estimator_command,
    validate_python_estimator_manifest,
)
from .gsc import (
    classify_gsc_failure,
    run_gsc_scope,
    run_python_gsc_scope,
    skip_after_structural_gsc_failure,
)
from .matching import fixed_control_output, run_cross_city_matching, run_frozen_control
from .mc import mc_family_run_output, mc_output, run_mc_scope, run_python_mc_scope
from .orchestrator import begin_mc_stage, process_one, run_mc_stage, write_task
from .runtime import HORIZONS, OUTCOMES, QueueSettings, settings
from .state import (
    _cohort_year,
    _month_key,
    control_for_order,
    effective_price_measure,
    new_run_id,
    queue_variant_path,
    read_control_queue,
    read_estimator_manifest,
    read_family_queue,
    read_orders_file,
    read_tasks_file,
    run,
    shard_order_slice,
    shard_queue_path,
    specification_fingerprint,
    sync_unit_queue,
    task_directory,
)
from .support import (
    _family_observed_grids,
    ensure_cross_city_viirs,
    ensure_viirs,
    family_has_observed_support,
    family_signature,
    viirs_has_full_matching_window,
    viirs_has_min_preperiods,
)
from .validation import (
    invalidate_stale_terminal_tasks,
    recover_completed_task,
    validate_task_labels,
    validate_task_manifest,
)

__all__ = [
    "HORIZONS",
    "OUTCOMES",
    "QueueSettings",
    "_cohort_year",
    "_family_observed_grids",
    "_month_key",
    "begin_mc_stage",
    "classify_gsc_failure",
    "control_for_order",
    "effective_price_measure",
    "eligible_indices",
    "ensure_cross_city_viirs",
    "ensure_viirs",
    "family_has_observed_support",
    "family_signature",
    "fixed_control_output",
    "gsc_output",
    "invalidate_stale_terminal_tasks",
    "main",
    "mc_family_run_output",
    "mc_output",
    "new_run_id",
    "normalized_python_labels",
    "process_one",
    "python_estimator_command",
    "queue_variant_path",
    "read_control_queue",
    "read_estimator_manifest",
    "read_family_queue",
    "read_orders_file",
    "read_tasks_file",
    "recover_completed_task",
    "run",
    "run_cross_city_matching",
    "run_frozen_control",
    "run_gsc_scope",
    "run_mc_scope",
    "run_mc_stage",
    "run_python_gsc_scope",
    "run_python_mc_scope",
    "settings",
    "shard_order_slice",
    "shard_queue_path",
    "skip_after_structural_gsc_failure",
    "specification_fingerprint",
    "sync_unit_queue",
    "task_directory",
    "validate_python_estimator_manifest",
    "validate_task_labels",
    "validate_task_manifest",
    "viirs_has_full_matching_window",
    "viirs_has_min_preperiods",
    "write_task",
]
